Feat: ground combat part 1
ZAB909/ChapterMaster pull request #120
Opened 2023-09-26 15:46 UTC by felipeStouvenel

# Feats:

## Finished the refactor for obj_star:

The following scripts were refactored and logic improvements alongside some documentation was added:
- Create_0
- Step_0
- Alarm_0
- Alarm_1
- Alarm_2
- Alarm_3
- Alarm_4
- Draw_0
- Mouse_50

### Next steps for ground combat (in future PRs):

- Create a new obj_planet_maps
- This object will contain some scripts to generate a map on creation of planets
- The first iteration would be to put this into the home system of the player, then once it works implement it to the sector generation.
- This will take some time, but will improve the chapter management and overall planet side gameplay, giving use to scouts and other units. Which would give reason to land on planets and not raid indefinitely.

2023-09-27 08:28 UTC, GalacticChimp commented on scripts/scr_star_name/scr_star_name.gml
please split this change out into a separate PR. Will be much easier to review, test, and if we'll have to revert the ground combat feature, we won't have to revert the star name improvements

2023-09-28 15:20 UTC, OH296 requested changes
not really sure if i'm doing this well, so don't feel obliged by any of it. Pretty much looks all good to me though.

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_0.gml
> -var a,b,c,d,e,f,g,h;
probably should be some different variable names to a,b,c etc.

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +            p_population[i] = floor(random(1500)) + 500;
irandom() instead of floor(random())? Maybe?

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +            case "Feudal":
missing break statement

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +            case "Desert":
break statement missing

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +                case "Forge":
break statement missing

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +                case "Feudal":
also break statements

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
> +                case "Hive":
break statements

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_1.gml
i know chimps been trying to get rid of un-needed comments not sure if this applies here?

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_4.gml
>      if (p_type[i]!="Dead") and (p_type[i]!="Lava"){// Used to not have Ice either
personally i've found if(!array_contains["dead", "lava", "ice"], p_type[i]){
}
to be a more extendable syntax
but it's all the same really

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_4.gml
> +                var ppp=instance_nearest(x,y,obj_p_fleet);
variable name ppp could be better

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Alarm_4.gml
again variable names particularly stue, stue2 could be better

2023-09-28 15:20 UTC, OH296 commented on objects/obj_star/Create_0.gml
>      p_upgrades[run]="";
p_upgrades are now lists so p_upgrades[run]=[];

2023-10-02 15:16 UTC, OH296 approved these changes
looks all good to me

2023-10-07 11:55 UTC, merged