Equipment cleanup
ZAB909/ChapterMaster pull request #257
Opened 2024-01-04 20:15 UTC by OH296

- general cleanup now new equipment is merged based on feedback and such
- all heavy_ranged weapons are now 2.25 ranged carry
- move from legacy temporary values to using struct based hp() method in combat
- port over to new json method for equipment abbreviations

2024-01-08 17:14 UTC, Blogaugis commented on scripts/scr_powers/scr_powers.gml
Would be nice if failed casting of psychic powers reward experience to the marine. Maybe even other marines as well.
Since, unsuccessful attempts tend to be more educational.

2024-01-10 15:55 UTC, renatosilvatimebel commented
getting an error as soon as it gets to the main menu screen after launching the game. the same doesnt happen on main branch.

`
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_main_menu_buttons:

Variable obj_main_menu_buttons.spr_settings_button(104744, -2147483648) not set before reading it.
 at gml_Object_obj_main_menu_buttons_Draw_0 (line 54) -         draw_sprite_stretched(spr_settings_button,0,0,room_height-48,48,48);
############################################################################################
gml_Object_obj_main_menu_buttons_Draw_0 (line 54)
`

2024-01-10 20:48 UTC, renatosilvatimebel commented
yeah, its the gear sprite from the main menu, i've double-checked and the sprite is there, this code dont directly change anything related with it, but this is the only branch that this happens. if i'm getting this, someone else will too.

can you try something, please? fully remove the cache and launch it again?

remove or rename the following folders:
C:\Users\YOUR_USER\AppData\Roaming\GameMakerStudio2
C:\Users\YOUR_USER\AppData\Local\GameMakerStudio2
C:\Users\YOUR_USER\AppData\Local\ChapterMaster (this is where your saves are)

this will hard clear all gamemaker cache and hopefully reproduce the bug.

2024-01-11 10:12 UTC, GalacticChimp commented on objects/obj_enunit/Alarm_0.gml
> -
👍

2024-01-11 10:18 UTC, GalacticChimp requested changes
looks fine. Please resolve merge conflicts and I'll merge this.

2024-01-22 01:11 UTC, merged

2024-01-25 12:13 UTC, Blogaugis commented on scripts/scr_weapon/scr_weapon.gml
> +       "abbreviation": "PoAxe",
This should be "PoFist".