corruption change and emissary bug
ZAB909/ChapterMaster pull request #258
Opened 2024-01-05 02:21 UTC by OH296

- Stops the CTD from the chaos emissary
- deprecates the use of obj_ini.chaos[company][unit] for unit.corruption
- this is ultimately laying the way to implementing corruption properly in the near future
- finishes all of the khorne options in the emissary allowing the you to make a sacrifice and in return receive khornes favour/attention (currently a trait called blood_for_blood)

2024-01-08 16:32 UTC, Blogaugis commented on scripts/scr_dialogue/scr_dialogue.gml
> +				diplo_text="Fetch this for her and you shll have their favour";
sh**a**ll
```suggestion
				diplo_text="Fetch this for her and you shall have their favour";
```

2024-01-08 16:44 UTC, Blogaugis commented on objects/obj_controller/Alarm_5.gml
It would be nice if chaos or daemonic artifacts (and other creations) would be more powerful and useful than standard counterparts.
Like 'fusion', where a marine is sacrificed option, should provide an opportunity, leading to an attempt to tame this vehicle, or otherwise acquire it under your control.
Chaos should be attractive option(s) after all.

2024-01-10 20:21 UTC, GalacticChimp commented
5 instances of `obj_ini.chaos` left:

![image](https://github.com/ZAB909/ChapterMaster/assets/63882831/d07ce2b1-0879-467e-a656-16caa2a9bede)

2024-01-10 20:25 UTC, GalacticChimp requested changes
please check my 2 comments

2024-01-10 20:25 UTC, GalacticChimp commented on objects/obj_controller/Mouse_50.gml
> +                pop_up.text = $"You summon {dead_champ.name_role()} to your personal chambers. Darting from the shadows {dead_champ.name()} is a cunning warrior and reacts with precision gowever even
```suggestion
                pop_up.text = $"You summon {dead_champ.name_role()} to your personal chambers. Darting from the shadows towards {dead_champ.name()} who is a cunning warrior and reacts with precision to your attack, however eventually you prevail and strike him down. With the flesh removed from his skull you place it upon a hastily erected shrine."
```

2024-01-11 10:12 UTC, GalacticChimp approved these changes

2024-01-11 10:12 UTC, merged