3 new squads and loadout balancing
ZAB909/ChapterMaster pull request #259
Opened 2024-01-09 19:58 UTC by KRdaMystic

Adds 3 squads assault terminators, vanguard and sternguard vets. Rebalances existing squad weapon loadouts.

2024-01-10 20:15 UTC, GalacticChimp commented
please also update

- obj_popup.Mouse_50.gml:

![image](https://github.com/ZAB909/ChapterMaster/assets/63882831/a6d19f79-f31d-4b1d-b32d-f0f9157c3211)

2024-01-10 20:16 UTC, GalacticChimp requested changes
just 1 more file needs to be updated as well

2024-01-11 17:46 UTC, KRdaMystic commented on scripts/scr_company_order/scr_company_order.gml
> +		["vanguard_veteran_squad",role[100][3],5],
Seems to generate both on my end at a ratio of 2-3

2024-01-12 22:24 UTC, GalacticChimp approved these changes

2024-01-12 22:24 UTC, merged